linki/chaoskube

README.md
main.go

proof-of-concept of `chaoskube` deploying itself into a cluster.
why? instead of manually fiddling with `kubectl` and manifest files wouldn't it be nice if `chaoskube` can take care of it?
demo:
```bash
$ kubectl proxy &
$ go get github.com/linki/chaoskube
$ chaoskube --deploy
$ kubectl get pods
NAME                               READY     STATUS    RESTARTS   AGE
chaoskube-93958562-tkuhv           1/1       Running   0          9s
```
is that a good idea? feedback welcome.

self-deploying chaoskube

---

chaoskube/chaoskube.go
chaoskube/chaoskube_test.go
main.go

This allows passing a label selector via 
```
$ chaoskube --labels "foo=bar,baz!=qux"
INFO[0000] Filtering pods by label selector: baz!=qux,foo=bar
```
It will filter the pods available for termination by that label selector.
Note, that also exclusions are possible via `!=`. In fact, it supports `'=', '!=', '==', 'in', notin'`.

allow victim pods to be selected via label selector

---

chaoskube/chaoskube.go
chaoskube/chaoskube_test.go
main.go

if `Victim()` didn't find a pod it would crash the main loop for now reason. This becomes more relevant when additional filters (e.g. by labels or namespace) lead to an empty set of pods.
Note: `chaoskube` still fatals in the loop on any other error. This is probably undesireable in most cases but I prefer a fail-early approach at the moment to make any other possible errors more visible.

do not choke when there's no victims

---

chaoskube/chaoskube.go
chaoskube/chaoskube_test.go
main.go

This allows filtering pods by arbitrary namespaces.
```
$ ./chaoskube --namespaces default,testing,staging
...
INFO[0000] Filtering pods by namespaces: default,staging,testing
```
This will filter for pods in the three namespaces default, staging and testing, not more.
It can be negated and combined with the label selector:
```
$ ./chaoskube --labels '!run,foo,app=mate' --namespaces '!kube-system,!production'
...
INFO[0000] Filtering pods by label selector: app=mate,foo,!run
INFO[0000] Filtering pods by namespaces: !kube-system,!production
```
This will select all pods that are not in the `kube-system` or `production` namespaces and have the label `app` with the value of `mate`, the label `foo` with any value and no `run` label with any value set.

allow filtering pods by namespace

---

.travis.yml

supporting the two most recent minor versions and now switching to go.19 and go1.8.

retire support for go 1.7

---

Dockerfile

Build using a single Dockerfile and also leads to a much smaller image. Also fixes https://github.com/linki/chaoskube/issues/36.

build using docker's multi-stage builds

---

.travis.yml

chore: drop go v1.8 from travis.yml

---

examples/chaoskube.yaml

Otherwise, you'll get `level=fatal msg="stat /root/.kube/config: no such file or directory"`

Use in-cluster config in example deployment

---

Dockerfile

fixes https://github.com/linki/chaoskube/issues/51
also switching to no-cache since we don't want to keep the cache on disk after we are done installing
@linki

add dumb-init

---

README.md
chaoskube/chaoskube.go
chaoskube/chaoskube_test.go
main.go
util/util.go
util/util_test.go

This is an alternative implementation of solely the weekday filter proposed in https://github.com/linki/chaoskube/pull/54. In my opinion it's simpler to understand and maintain than https://github.com/linki/chaoskube/pull/54 (It also does less at this point).
It adds a flag to specify a list of weekdays when chaoskube doesn't terminate any pods, e.g. specifying `--excluded-weekdays "sat,sun"` would prevent any chaos on the weekend. I picked the `exclude-`-approach so that the default empty `--excluded-weekdays=""` would behave as before.
@klautcomputing @twildeboer This idea comes directly from your PRs  https://github.com/linki/chaoskube/pull/47 and https://github.com/linki/chaoskube/pull/54 but I focused on the weekday filter first in order to keep it simpe. I intend to look through …

Allow to suspend chaoskube at certain weekdays

---

Dockerfile

current image
* fails to connect to AWS clusters
* cannot read timezone information other than Local and UTC

Add certificates and timezone info to docker image

---

Gopkg.lock
README.md
chaoskube/chaoskube.go
chaoskube/chaoskube_test.go
main.go
util/util.go
util/util_test.go

allows to specify time periods per day that chaoskube is inactive, e.g.
```
--excluded-times-of-day="11:00-13:00,22:00-06:00"
```

Allow to specify daily time periods without chaos

---

util/util.go

Also ignores the time zone when merely parsing a string into a struct.

Raise error on malformed time range

---

README.md
chaoskube/chaoskube.go
chaoskube/chaoskube_test.go
main.go
util/util.go
util/util_test.go

There's one last feature contained in https://github.com/linki/chaoskube/pull/55 about excluding certain dates. Porting it over to the latest master.

Allow to exclude certain dates from chaos

---

chaoskube/chaoskube.go
chaoskube/chaoskube_test.go
main.go

For #85 
Optionally filter pods based on age, excluding those that are not older than the passed minimum age.
I added a test specifically for the age check.

Add minimum age check for pods

---

chaoskube/chaoskube.go
chaoskube/chaoskube_test.go

I think it's receommended to use the versioned funcs to get the client object.

Use versioned funcs of client-go

---

README.md
main.go

For #93 
This creates a very simple HTTP endpoint to be used for liveness and readiness checks. In this initial version, it only returns OK. In the future, we may want to check additional functionality before returning OK.
We can reuse this listener for things such as prometheus metrics, as mentioned in #23, in the future, if desired.

Add simple healthz handler

---

chaoskube/chaoskube.go
chaoskube/chaoskube_test.go
main.go

This improves graceful shutdown by handling signals and not using sleep.

Handle signals for graceful shutdown

---

Gopkg.lock
Gopkg.toml
main.go

This is based on #93 which added the HTTP listener.
This adds the Prometheus metrics handler but does not record any application specific metrics.  I think we may want to wait until #95 is merged before adding metrics as that PR changed the structure of how the loop is ran.
I had to "fix" the protobuf dependency to get this to work with the addition of Prometheus.

Initial Proemtheus metrics support

---

README.md
chaoskube/chaoskube.go
chaoskube/chaoskube_test.go
examples/rbac.yaml
main.go
util/util.go

Currently chaoskube logs the termination of pods only to stdout. This patch implements the creation of a Kubernetes Event in victims namespace so users which cannot access chaoskubes logs can see who terminated their pod. There is a new flag to disable this feature.
Event looks like:
```
$ kubectl get events
LAST SEEN   FIRST SEEN   COUNT     NAME                                       KIND        SUBOBJECT                      TYPE      REASON         SOURCE                            MESSAGE
56s         56s          1         calico-node-tj5pq.chaos.15543f44b237b716   Pod                                        Normal    Chaos                                            Deleted pod calico-node-tj5pq
```
RBAC rules were extended to allow this function.

Implement event creation after terminating a pod

---

Gopkg.lock
Gopkg.toml
examples/chaoskube.yaml

This replaces `glog` with `github.com/kubermatic/glog-logrus` which allows to inject a `logrus` logger instead (the default is a noop logger). Replacing glog allows us to set `readOnlyRootFilesystem: true`.
It also updates the example deployment file with all the settings recommended by [https://kubesec.io/](https://kubesec.io/). Thanks to all the previous work: be able to run as non-root etc. (read-only fs was the last missing one).
Thanks to @kdomanski for `github.com/kubermatic/glog-logrus`.

Replace glog and allow to reduce container privileges

---

chaoskube/chaoskube.go
chaoskube/chaoskube_test.go
main.go

This PR adds a `--grace-period` option to be able to follow different pod termination policies (gracefully vs non-gracefully). The default value is 30, that is the default grace period used by Kubernetes.
Related #103
Closes #80

feat: add grace period option to terminate pods

---

Gopkg.lock
chaoskube/chaoskube.go
chaoskube/chaoskube_test.go
main.go
util/util.go

Replaces the feature of exporting events from https://github.com/linki/chaoskube/pull/105 to use Kubernetes' EventRecorder.
With this:
* exporting events is enabled by default and cannot be turned off
* events are attached to the Pod being killed as opposed to the namespace it's in
* `kubectl get events` can be used to show the events, see line four below.
```console
$ kubectl get events
LAST SEEN   FIRST SEEN   COUNT     NAME                                              KIND         SUBOBJECT                 TYPE      REASON             SOURCE                                            MESSAGE
2m          2m           1         tiller-deploy-557f85548b-7x9dj.156afef7a3d9f6ef   Pod                                    Normal    Scheduled          default-scheduler …
```

Replace event related code with Kube's EventRecorder

---

.travis.yml
Gopkg.lock
chaoskube/chaoskube.go
chaoskube/chaoskube_test.go
metrics/metrics.go

PR [#102](https://github.com/linki/chaoskube/pull/102) adding useful prometheus-metrics by @shaikatz was unfortunately closed. Credits to @shaikatz for his efforts. 👍 It seems there are no further attempts to get this merged. He might be busy with other works ;) I have rebased the same old PR [#102](https://github.com/linki/chaoskube/pull/102) with the updated chaoskube code and hoping we can get this merged this time.
@shaikatz if you are still following this project your comments are highly apreciated. 👍

Rebase PR #102 and update - prometheus metrics

---

Dockerfile.arm32v6

Add arm32v6 compatible docker image to support devices like Raspberry Pi 2/3 etc.

Add Dockerfile.arm32v6

---

Gopkg.lock
chaoskube/action.go
chaoskube/chaoskube.go
chaoskube/chaoskube_test.go
main.go

This is a proposal to introduce alternative means of killing
pods, outside of simply asking kubernetes to stop them.
Specifically, it allows executing a shell command on a victim
container; that shell command can then be a simple kill -9,
a fork bomb, or any other means of destruction.
There are, at least, two reasons why this is useful. First,
it gives an option of more realistic failures. Simply deleting
a pod is a rather kind way to stop a pod - in reality a pod is likely
to go down in flames from lack of memory, segfaulting or instant
hardware failure. This brings the chaos closer to reality.
The second reason is that this helps test operators that directly
manipulate pods, rather than rely on higher-level concepts like
StatefulSets, Deployments and so on. In this case, the thing we …

Initial sketch of --exec

---

CHANGELOG.md
README.md
chaoskube/chaoskube.go
chaoskube/chaoskube_test.go
main.go

This PR adds parameters that allow pod to be filtered in/out by pod name.  This is a useful feature because some existing Kubernetes applications (the one I work on is an example) don't have the necessary labels that are required to make use of the existing chaoskube label selector filtering.  So for those users, this just allows them to provide a simple regex pattern for pod names to include and to exclude.
Also includes:
- README updates to indicate the new usage
- Necessary test updates, including verifying the new capability in TestCandidates().

Add include/exclude filters for pod names

---

README.md
main.go

Adds `--log-caller` to allow printing the function's name and location as part of the log line.

Allow to log function name and location

---

README.md
chaoskube/chaoskube.go
chaoskube/chaoskube_test.go
main.go
util/util.go
util/util_test.go

Allows to provide a label selector for namespaces. This can be used to limit chaoskube's action to all namespaces that match a certain label selector.
Based on https://github.com/linki/chaoskube/pull/46 and https://github.com/swestcott/chaoskube/pull/1 and rebased on master.
Thanks @swestcott for the initial work.
Implements https://github.com/linki/chaoskube/issues/44
Replaces  https://github.com/linki/chaoskube/pull/46 and https://github.com/swestcott/chaoskube/pull/1

Allow to filter pods by namespace label selector

---

README.md

The snippet from README was confusing, because it didn't contain
appropriate ServiceAccount and ClusterRole configuration to give
ChaosKube necessary permissions. It took me a moment to figure out why I
was getting `pods is forbidden:` error.

README: remove inclomplete snippet, point to examples

---

CHANGELOG.md
chaoskube/chaoskube.go
chaoskube/chaoskube_test.go
go.mod
main.go
util/util.go
util/util_test.go

The configuration flag --max-kill specifies the maximum number of pods to be terminated per run,
with a default value of 1, to maintain existing behavior.
Adds a new filter: filterByOwnerReference to avoid terminating multiple pods belonging to the
same owner. This prevents pods deployed together to be terminated at the same time.
In practice, no more than 1 pod per owner will be terminated during each run. All pods without an owner
reference are eligible to be terminated in the same batch (up to --max-kill value)
This a PoC to address https://github.com/linki/chaoskube/issues/152
@linki if you think this is a good approach, I'll add tests for the new behavior.
For context, this is very helpful for large clusters. With a `--max-kill=10` we can now terminate up to 10 pods per run, and most …

Adds support for terminating multiple pods per run

---

README.md

It looks the feature is already released https://github.com/linki/chaoskube/pull/158 & a new docker image `quay.io/linki/chaoskube:v0.17.0` is ready. Can we add the flag on README or on the examples dir!

Add slack webhook flag to documentation

---

chaoskube/chaoskube.go
chaoskube/chaoskube_test.go
terminator/delete_pod.go
terminator/delete_pod_test.go
terminator/terminator.go

Now that client-go [supports a context](https://github.com/linki/chaoskube/pull/191) parameter we can actually support it in chaoskube as well.
I've never used context for anything else other than signal handling (like in chaoskube's main loop) and request timeouts. Both could be applied here but for now I'll use it for the former.
Before, if for some reason the call to the Kubernetes API was hanging, hitting Ctrl+C would just not work. Although the top-level context would have its cancel func called, we'd never read the Done channel until the request is completed, e.g. via some timeout.
Now, the top-level cancellable context is propagated down to client-go and Ctrl+C will actually preempt long running requests and the program can terminate immediately.

Use context to cancel in-flight requests

---

chaoskube/chaoskube.go

This got lost somehow.
It's useful to see whether the candidate selection or the victim picking is wrong, see https://github.com/linki/chaoskube/issues/197#issuecomment-615253281.

Log found candicates as well

---

chaoskube/chaoskube.go
chaoskube/chaoskube_test.go

Fix for https://github.com/linki/chaoskube/issues/197

Ensure a random pod is picked within an owner reference group

---

.gitignore
Makefile

References: #146 
Added `make test` &  `make build`
test - Since check is already added, test redirects and runs `make check`
build - added `make build` to run `go build` and generate the binary in `bin/chaoskube`

Added test & build to makefile

---

README.md
chaoskube/chaoskube.go
chaoskube/chaoskube_test.go
examples/chaoskube.yaml
main.go
util/util.go

This PR adds new flag `--kinds`. 
It allows us to include/exclude specific Kinds of pods or, to be more specific, filter by OwnerReference's Kind.
So, for example, you can exclude any pods created by any DaemonSet by using the following flag:
```
--kinds="!DaemonSet"
```

Filter by OwnerReference's Kind

---

.github/workflows/helm.yml
chart/chaoskube/.helmignore
chart/chaoskube/Chart.yaml
chart/chaoskube/README.md
chart/chaoskube/templates/NOTES.txt
chart/chaoskube/templates/_helpers.tpl
chart/chaoskube/templates/clusterrole.yaml
chart/chaoskube/templates/clusterrolebinding.yaml
chart/chaoskube/templates/deployment.yaml
chart/chaoskube/templates/serviceaccount.yaml
chart/chaoskube/values.yaml

Quickly hacked together, needs some detailing. Waiting on feedback 😃 See also #275  You can already run `helm template chart/chaoskube/` to see/apply the rendered manifests

add a helm chart to deploy chaoskube

---

README.md
examples/deployment/chaoskube.yaml
examples/job/chaoskube.yaml
examples/rbac.yaml
main.go

This could be the solution to the #271, regarding the flag, which gracefully shuts down chaoskube.

Add maximum runtime flag

---

chaoskube/chaoskube.go
metrics/metrics.go

Adds the namespace as a label to the pods_deleted metric. The result looks like this:
Fixes https://github.com/linki/chaoskube/issues/150
```console
chaoskube_pods_deleted_total{namespace="baz"} 1
chaoskube_pods_deleted_total{namespace="api"} 1
chaoskube_pods_deleted_total{namespace="cassandra"} 1
chaoskube_pods_deleted_total{namespace="foobar"} 1
chaoskube_pods_deleted_total{namespace="default"} 27
chaoskube_pods_deleted_total{namespace="kube-system"} 31
chaoskube_pods_deleted_total{namespace="github"} 1
chaoskube_pods_deleted_total{namespace="myspace"} 1
chaoskube_pods_deleted_total{namespace="other"} 4
```

Add namespace metadata to deleted pods metric

---

.github/dependabot.yml

Let dependabot update github actions
as described in https://github.com/docker/build-push-action/blob/7c41daf2a5f378ed47e2c3e4da5152f52281f6a4/README.md#keep-up-to-date-with-github-dependabot

Let Dependabot update GitHub Actions

---

.github/workflows/container-image.yml

We're using the tags to determine the version within the Dockerfile. Let's see if this gets it back.
* The checkout action's checkout is ignored during the build-and-push phase unless `context: .` is used.
* The checkout action doesn't fetch any git tags. So add another action that fetches them.

Fetch all git tags after shallow checkout and use the path context

---

.github/dependabot.yml

It currently creates a lot of pointless PRs each week because they are not reviewed/merged. Let's reduce the interval to monthly to reduce the noise.

Switch dependabot interval from weekly to monthly

---

chart/chaoskube/templates/deployment.yaml
chart/chaoskube/values.yaml

This adds the support to add `envFrom` with `configMapRef ` through Helm Values:
I wasn't able to use an array of maps with the current setup, like this:
```yaml
chaoskube:
env:
- name: MY_VAR
valueFrom:
configMapKeyRef:
name: chaoskube-cm1
key: my-var
```
Results in: error converting YAML to JSON: yaml: line 39: did not find expected key
With this PR it will be possible to add the following: 
```yaml
chaoskube:
envFromConfigMapRefs:
- chaoskube-cm1
- chaoskube-cm2
```
What do you think, could this be merged?

feat: add envFrom ConfigMap to chart

---

chart/chaoskube/templates/deployment.yaml
chart/chaoskube/values.yaml

Hi Chaoskube Team,
we need to label all of our resources in our k8s clusters. Sometimes for human purpose, sometimes for technical purpose (f.e. NetworkPolicies).
I noticed that your helm chart does not yet offer the possibility to specify additional Labels that will be applied to the Deployment and the pods, so I created this PR.
Any feedback is appreciated.
Thanks!

Add additionalLabels to values and deployment

---

chart/chaoskube/Chart.yaml

Chart has changed and requires a new version. Also bump chaoskube's version.
* https://github.com/linki/chaoskube/pull/521
* https://github.com/linki/chaoskube/pull/522

update chart with additional configurable fields

---

chart/chaoskube/Chart.yaml

The app version in the helm chart is outdated. 
We would like to upgrade to the latest version of Chaoskube.

chore(helm): upgrade chart to use appVersion 0.32.0
