- .travis.yml
- README.md
- chaoskube/chaoskube.go
- chaoskube/chaoskube_test.go
- main.go
extract and test the current victim finder logic in order to extend it with a more sophisticated one.
> extract finder and add tests

- chaoskube/chaoskube.go
- chaoskube/chaoskube_test.go
- main.go
promote `TerminateVictim()` to `chaoskube` for easier calling from main and testing.
> promote terminate victim to method

- .travis.yml
have travis run tests with go1.8
> add go1.8 to travis.yml

- README.md
- chaoskube/chaoskube.go
- chaoskube/chaoskube_test.go
- main.go
allows to filter pods by annotations
> filter pods by annotations

- Dockerfile
Changes in this PR:
- use newer alpine version
- drop to non root user
> Drop to chaoskube user

- examples/chaoskube.yaml
- examples/rbac.yaml
Here is a copy of what I used to deploy this in a cluster that uses rbac.
> Adds rbac example

- Dockerfile
Forgot this. Thanks quay.io for letting me know.
> Use dep in Dockerfile as well

- chaoskube/chaoskube_test.go
Refactors the test cases to make more use of table tests which cleans them up quite a bit.
> Consolidate into table tests for maintainability

- Gopkg.lock
- Gopkg.toml
- chaoskube/chaoskube_test.go
- util/util_test.go
> Refactor tests using testify

- .travis.yml
- Dockerfile
update to go 1.10 and alpine 3.7
> Update to go 1.10 and alpine 3.7

- chaoskube/chaoskube.go
- chaoskube/chaoskube_test.go
- main.go
It doesn't really belong there I think.
> Move seeding out of chaoskube struct

- chaoskube/chaoskube.go
- chaoskube/chaoskube_test.go
- main.go
- util/util.go
Looks cleaner and helps structuring the logs imo.
> Switch to tagged logging

- README.md
- chaoskube/chaoskube.go
- examples/chaoskube.yaml
- examples/rbac.yaml
- main.go
Updates the docs to the latest version as well as mentions other contributors and related work.
> docs cleanup, related work and acknowledgements

- Gopkg.lock
- Gopkg.toml
- chaoskube/chaoskube.go
- chaoskube/chaoskube_test.go
- util/util.go
make it work with kubernetes 1.10
> Bump client-go to v7 and k8s to v1.10

- .travis.yml
- CHANGELOG.md
- Dockerfile
- Dockerfile.ppc64le
bring both to the latest versions
> Update docker image to go1.11 and alpine3.8

- Gopkg.lock
- Gopkg.toml
- main.go
update client-go to v9 as well.
> Update depedencies to kubernetes v1.12

- Dockerfile.arm64v8
Add arm64v8 compatible with scaleway's arm instances.
> Build image for arm64v8

- chaoskube/chaoskube_test.go
- main.go
https://golangci.com/r/github.com/linki/chaoskube
> Change code according to golangci's recommendations

- main.go
Just moves the code into a separate function + some minor cleanup.
> Extract metrics serving into separate function

- go.mod
- main.go
Fixes https://github.com/linki/chaoskube/issues/137
> Avoid writing klogs to the filesystem

- README.md
> Update Helm's Quickstart Guide link in README

- README.md
Added `--max-kill` flag doc to README.md
Because it was missing.
> Add missing max-kill flag missing doc

- terminator/delete_pod.go
- terminator/delete_pod_test.go
> bugfix: pod termination grace period

- Dockerfile
Change binary location in the container to `/usr/local/bin/chaoskube` (because why not 🤷 ).
> Change binary location in the container to /usr/local/bin

- .travis.yml
- Dockerfile
- go.mod
> Update Golang to v1.18

- .github/workflows/container-image.yml
Based on https://github.blog/2021-12-06-safeguard-container-signing-capability-actions/
> Sign container images with OIDC token

- main.go
change log.Fileds for JSON format output.
> chore: change log.Fileds for JSON format output

- .github/workflows/container-image.yml
see also: https://github.com/docker/build-push-action/issues/687#issuecomment-1651816012
> Configure permissions for github action to address error
